# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
#  heroku: circleci/heroku@1.2.6

workflows:
  default: 
    jobs:
      - build-and-test
#  heroku_deploy:
#    jobs:
#      - build-and-test
#      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
#          requires:
#            - build-and-test
#          filters:
#            branches:
#              only: master

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
